spring:
  datasource:
    url: jdbc:mysql://database-1.cudzkfqxd95s.ap-northeast-2.rds.amazonaws.com/test_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: asdf1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update create none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: localhost
    port: 6379

  level:
    org:
      hibernate:
        type: trace