spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springjpa?MVCC=TRUE&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: whdgns1002@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # update create auto
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  level:
    org:
      hibernate:
        type: trace
#  logging.level.org.springframework: debug
#  logging.level.org.springframework.web: debug
