spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?MVCC=TRUE&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: whdgns1002@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update create none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        temp:
#          use_jdbc_metadata_defaults: false;
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect




